import type { Metadata } from "next";
import "../globals.css";
import { inter } from "@/lib/fonts";


export const metadata: Metadata = {
  title: {
    default: "EAUT | Trang thông tin dành cho sinh viên",
    template: "EAUT | %s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
