import type { Metadata } from 'next';
import '../globals.css';
import { inter } from '@/lib/fonts';
import { ThemeProvider } from 'next-themes';

export const metadata: Metadata = {
	title: {
		default: 'EAUT | Trang thông tin dành cho sinh viên',
		template: 'EAUT | %s',
	},
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className={inter.className}>
				<ThemeProvider
					attribute='class'
					defaultTheme='light'
					enableSystem
					disableTransitionOnChange
				>
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
