import type { Metadata } from "next";
import "../globals.css";
import { inter } from "@/lib/fonts";
import Providers from "@/components/providers";
import Footer from "@/components/shared/footer";
import Header from "@/components/shared/header/header";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: {
    default: "EAUT | Trang thông tin dành cho sinh viên",
    template: "EAUT | %s",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className} text-foreground md:space-y-3`}>
        <Providers>
          <Suspense>
            <Header />
          </Suspense>
          <main className="container min-h-screen space-y-3 bg-background text-foreground">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
